// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVdS0Q_7YC0F9XeyVBHwxhUL3FTDkDM-8',
    appId: '1:901845561410:web:fb72177bf3b93b2ed07ddb',
    messagingSenderId: '901845561410',
    projectId: 'lifeinapp',
    authDomain: 'lifeinapp.firebaseapp.com',
    storageBucket: 'lifeinapp.firebasestorage.app',
    measurementId: 'G-K4MNBYW29D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuB2uyVtcrBXW_eypQhq_wIK2ajIngdJI',
    appId: '1:901845561410:android:a2c7b2c4c287c997d07ddb',
    messagingSenderId: '901845561410',
    projectId: 'lifeinapp',
    storageBucket: 'lifeinapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkYrHlFlcA0xHwv4lOwQXs-AHCHVaFpg4',
    appId: '1:901845561410:ios:da742a21da3cf073d07ddb',
    messagingSenderId: '901845561410',
    projectId: 'lifeinapp',
    storageBucket: 'lifeinapp.firebasestorage.app',
    iosBundleId: 'com.example.lifeinapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkYrHlFlcA0xHwv4lOwQXs-AHCHVaFpg4',
    appId: '1:901845561410:ios:da742a21da3cf073d07ddb',
    messagingSenderId: '901845561410',
    projectId: 'lifeinapp',
    storageBucket: 'lifeinapp.firebasestorage.app',
    iosBundleId: 'com.example.lifeinapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVdS0Q_7YC0F9XeyVBHwxhUL3FTDkDM-8',
    appId: '1:901845561410:web:b65b39896cae4c94d07ddb',
    messagingSenderId: '901845561410',
    projectId: 'lifeinapp',
    authDomain: 'lifeinapp.firebaseapp.com',
    storageBucket: 'lifeinapp.firebasestorage.app',
    measurementId: 'G-V4P9YWQNJP',
  );
}
