name: Build and Sign iOS
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'
      - run: flutter pub get
      - run: cd ios && pod install && cd ..  # Install iOS dependencies

      # Decode signing certificate and provisioning profile
      - name: Decode Signing Certificate
        run: |
          echo "${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}" | base64 --decode > ios.p12
      - name: Decode Provisioning Profile
        run: |
          echo "${{ secrets.PROVISIONING_PROFILE_DATA }}" | base64 --decode > ios.mobileprovision

      # Build and sign the iOS app
      - name: Build and Sign IPA
        run: |
          flutter build ios --release
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          xcrun -sdk iphoneos codesign -f -s "iPhone Developer" -p ios.p12 --password "${{ secrets.CERTIFICATE_PASSWORD }}" Payload/Runner.app
          zip -r app.ipa Payload
          ls -la  # Debug: Verify app.ipa exists

      # Upload the IPA
      - uses: actions/upload-artifact@v3
        with:
          name: signed-ios-app
          path: app.ipa